// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_layout from "./routes/admin/_layout.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_event from "./routes/admin/event.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_movie from "./routes/admin/movie.tsx";
import * as $admin_user from "./routes/admin/user.tsx";
import * as $all_components from "./routes/all-components.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $bng from "./routes/bng.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $user_layout from "./routes/user/_layout.tsx";
import * as $user_bng from "./routes/user/bng.tsx";
import * as $user_event from "./routes/user/event.tsx";
import * as $user_index from "./routes/user/index.tsx";
import * as $user_logout from "./routes/user/logout.tsx";
import * as $user_movie from "./routes/user/movie.tsx";
import * as $user_poll from "./routes/user/poll.tsx";
import * as $Button from "./islands/Button.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $EventIsland_EventIsland from "./islands/EventIsland/EventIsland.tsx";
import * as $FormIsland_FormIsland from "./islands/FormIsland/FormIsland.tsx";
import * as $MovieIsland_MovieIsland from "./islands/MovieIsland/MovieIsland.tsx";
import * as $event_Event from "./islands/event/Event.tsx";
import * as $event_RSVPStatus from "./islands/event/RSVPStatus.tsx";
import * as $event_StatusLabel from "./islands/event/StatusLabel.tsx";
import * as $form_CheckboxField from "./islands/form/CheckboxField.tsx";
import * as $form_InputField from "./islands/form/InputField.tsx";
import * as $form_LabelGroup from "./islands/form/LabelGroup.tsx";
import * as $form_SelectField from "./islands/form/SelectField.tsx";
import * as $form_mod from "./islands/form/mod.ts";
import * as $movie_Movie from "./islands/movie/Movie.tsx";
import * as $stars_Star from "./islands/stars/Star.tsx";
import * as $stars_Stars from "./islands/stars/Stars.tsx";
import * as $util_index from "./islands/util/index.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/_layout.tsx": $admin_layout,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/event.tsx": $admin_event,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/movie.tsx": $admin_movie,
    "./routes/admin/user.tsx": $admin_user,
    "./routes/all-components.tsx": $all_components,
    "./routes/api/joke.ts": $api_joke,
    "./routes/bng.tsx": $bng,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/user/_layout.tsx": $user_layout,
    "./routes/user/bng.tsx": $user_bng,
    "./routes/user/event.tsx": $user_event,
    "./routes/user/index.tsx": $user_index,
    "./routes/user/logout.tsx": $user_logout,
    "./routes/user/movie.tsx": $user_movie,
    "./routes/user/poll.tsx": $user_poll,
  },
  islands: {
    "./islands/Button.tsx": $Button,
    "./islands/Counter.tsx": $Counter,
    "./islands/EventIsland/EventIsland.tsx": $EventIsland_EventIsland,
    "./islands/FormIsland/FormIsland.tsx": $FormIsland_FormIsland,
    "./islands/MovieIsland/MovieIsland.tsx": $MovieIsland_MovieIsland,
    "./islands/event/Event.tsx": $event_Event,
    "./islands/event/RSVPStatus.tsx": $event_RSVPStatus,
    "./islands/event/StatusLabel.tsx": $event_StatusLabel,
    "./islands/form/CheckboxField.tsx": $form_CheckboxField,
    "./islands/form/InputField.tsx": $form_InputField,
    "./islands/form/LabelGroup.tsx": $form_LabelGroup,
    "./islands/form/SelectField.tsx": $form_SelectField,
    "./islands/form/mod.ts": $form_mod,
    "./islands/movie/Movie.tsx": $movie_Movie,
    "./islands/stars/Star.tsx": $stars_Star,
    "./islands/stars/Stars.tsx": $stars_Stars,
    "./islands/util/index.ts": $util_index,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
