// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_layout from "./routes/admin/_layout.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_users from "./routes/admin/users.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $user_layout from "./routes/user/_layout.tsx";
import * as $user_event from "./routes/user/event.tsx";
import * as $user_index from "./routes/user/index.tsx";
import * as $user_logout from "./routes/user/logout.tsx";
import * as $Button from "./islands/Button.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $form_InputField from "./islands/form/InputField.tsx";
import * as $form_SelectField from "./islands/form/SelectField.tsx";
import * as $form_mod from "./islands/form/mod.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/_layout.tsx": $admin_layout,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/users.tsx": $admin_users,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/user/_layout.tsx": $user_layout,
    "./routes/user/event.tsx": $user_event,
    "./routes/user/index.tsx": $user_index,
    "./routes/user/logout.tsx": $user_logout,
  },
  islands: {
    "./islands/Button.tsx": $Button,
    "./islands/Counter.tsx": $Counter,
    "./islands/form/InputField.tsx": $form_InputField,
    "./islands/form/SelectField.tsx": $form_SelectField,
    "./islands/form/mod.ts": $form_mod,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
