name: Test
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Lint
        run: "deno fmt --check"

      - name: Install SQLite
        uses: actions/setup-sqlite@v1
        with:
          sqlite-version: 3.40.0
          sqlite-year: 2022

      - name: Test
        env:
          DB_PATH: test.db
        run: |
          deno run db:migrateAll
          deno run test
